### ISSUE TITLE
Settings panel won't open [dev branch]

### ISSUE THREAD

**Issue by Jip-Hop** [MarginallyClever/Makelangelo-software#288]
Hi Dan,

When I compile Makelangelo from the head of dev and press the Settings button, I get the following error:

```
2020-06-26 14:42:37 adjust window size...
2020-06-26 14:42:37   make visible...
2020-06-26 14:42:38   adding drag & drop support...
2020-06-26 14:42:38   starting animator...
2020-06-26 14:42:38 checking sharing permissions...
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')
	at com.marginallyclever.makelangelo.select.SelectFloat$1.validate(SelectFloat.java:68)
	at com.marginallyclever.makelangelo.select.SelectFloat$1.insertUpdate(SelectFloat.java:55)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
	at java.desktop/javax.swing.text.JTextComponent.setText(JTextComponent.java:1729)
	at java.desktop/javax.swing.JFormattedTextField$AbstractFormatter.install(JFormattedTextField.java:957)
	at java.desktop/javax.swing.text.DefaultFormatter.install(DefaultFormatter.java:125)
	at java.desktop/javax.swing.text.InternationalFormatter.install(InternationalFormatter.java:286)
	at java.desktop/javax.swing.JFormattedTextField.setFormatter(JFormattedTextField.java:474)
	at java.desktop/javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:797)
	at java.desktop/javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:511)
	at com.marginallyclever.makelangelo.select.SelectFloat.setValue(SelectFloat.java:130)
	at com.marginallyclever.makelangeloRobot.settings.PanelAdjustMachine.updateLengthNeeded(PanelAdjustMachine.java:96)
	at com.marginallyclever.makelangeloRobot.settings.PanelAdjustMachine.<init>(PanelAdjustMachine.java:83)
	at com.marginallyclever.makelangeloRobot.settings.MakelangeloSettingsDialog.rebuildTabbedPanes(MakelangeloSettingsDialog.java:167)
	at com.marginallyclever.makelangeloRobot.settings.MakelangeloSettingsDialog.run(MakelangeloSettingsDialog.java:76)
	at com.marginallyclever.makelangeloRobot.MakelangeloRobotPanel.actionPerformed(MakelangeloRobotPanel.java:497)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I traced the bug back to commit 3e3889a7dc8e56619d49862df502b911abb31625. The Settings panel won't open anymore from then on.

**Comment by i-make-robots** [comment]
I'm not able to reproduce this error.

**Comment by i-make-robots** [comment]
silent exception?  Uhhh.... great.

**Comment by i-make-robots** [comment]
Uh, I just poked it in e506121d30cb80a8c95173dba9cfac05bfffe6e8 and listed the wrong bug fix.  Oops.

**Comment by Jip-Hop** [comment]
Yay I can open the settings panel again 😄
