### ISSUE TITLE
Github Maven Surefire timeout crash in CI Action

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#363]
**Steps to make the bug happen**
1. Run the Github Aaction "build".  Watch output until timeout

**What was supposed to happen**
All tests pass, project builds, nightly release updated.

**Platform (please complete the following information):**
 - Github latest

**Log file**
[logs_397-1.zip](https://github.com/MarginallyClever/Makelangelo-software/files/7591849/logs_397-1.zip)

**Additional context**
```[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:56 min
[INFO] Finished at: 2021-11-23T22:20:48Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project Makelangelo: There are test failures.
Error:  
Error:  Please refer to D:\a\Makelangelo-software\Makelangelo-software\target\surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was cmd.exe /X /C "C:\hostedtoolcache\windows\jdk\17.0.1\x64\bin\java @C:\Users\runneradmin\AppData\Local\Temp\surefire5887936722090907777\surefireargs16801382018128051631 C:\Users\runneradmin\AppData\Local\Temp\surefire5887936722090907777 2021-11-23T22-06-02_126-jvmRun1 surefire15607244870506140050tmp surefire_05451778634325515287tmp"
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 1
Error:  Crashed tests:
Error:  com.marginallyclever.makelangelo.TranslatorTests
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was cmd.exe /X /C "C:\hostedtoolcache\windows\jdk\17.0.1\x64\bin\java @C:\Users\runneradmin\AppData\Local\Temp\surefire5887936722090907777\surefireargs16801382018128051631 C:\Users\runneradmin\AppData\Local\Temp\surefire5887936722090907777 2021-11-23T22-06-02_126-jvmRun1 surefire15607244870506140050tmp surefire_05451778634325515287tmp"
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 1
Error:  Crashed tests:
Error:  com.marginallyclever.makelangelo.TranslatorTests
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
Error:  	Terminate batch job (Y/N)? 
Error: The action has timed out.```

**Comment by martin-g** [comment]
You should have a hs_err***.txt file created by the JVM after the crash. It should have information what causes the crash.
