### ISSUE TITLE
PNG Image do not load

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#383]
**Steps to make the bug happen**
1. File > Open File
2. Select a png
3. an empty dialog with an error title is displayed and the application is frozen
![image](https://user-images.githubusercontent.com/23615562/146974055-aabcabf7-f68f-476e-9e4d-9a5f1ce14a6d.png)

**What was supposed to happen**
The image should be loaded

**Platform (please complete the following information):**
 - Version: 7.30.2
 - OS: macos 11.6

**Log file**
[log.txt](https://github.com/MarginallyClever/Makelangelo-software/files/7757060/log.txt)

**Additional context**
loading JPEG also failed

**Comment by i-make-robots** [comment]
Confirmed.  In the error message I get

    Cannot invoke "com.marginallyclever.makelangelo.makeArt.TransformedImage.canSampleAt(double,double)" because "this.myImage" is null

Which is very cryptic.  It looks to me like a failure inside ConvertImagePanel.

**Comment by i-make-robots** [comment]
On a separate note, "Missing: Error" is silly.  Your system shows blank for `e.getLocalizedMessage()` while the log file probably shows the message correctly with `"Load error:"+e.getMessage()`

**Comment by coliss86** [comment]
I have added a `printStackTrace()` : 
```
java.lang.NullPointerException: Cannot invoke "com.marginallyclever.makelangelo.makeArt.TransformedImage.canSampleAt(double, double)" because "this.myImage" is null
	at com.marginallyclever.makelangelo.makeArt.imageConverter.Converter_VoronoiStippling.initializeCells(Converter_VoronoiStippling.java:333)
	at com.marginallyclever.makelangelo.makeArt.imageConverter.Converter_VoronoiStippling.restart(Converter_VoronoiStippling.java:209)
	at com.marginallyclever.makelangelo.makeArt.imageConverter.Converter_VoronoiStippling.propertyChange(Converter_VoronoiStippling.java:177)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8722)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1187)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1179)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1187)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1179)
	at java.desktop/java.awt.Component.setGraphicsConfiguration(Component.java:1167)
	at java.desktop/java.awt.Container.addImpl(Container.java:1140)
	at java.desktop/java.awt.Container.add(Container.java:440)
	at com.marginallyclever.makelangelo.makeArt.io.LoadFilePanel.load(LoadFilePanel.java:88)
	at com.marginallyclever.makelangelo.makeArt.io.LoadFilePanel.chooseFile(LoadFilePanel.java:74)
	at com.marginallyclever.makelangelo.makeArt.io.LoadFilePanel.lambda$getFileSelectionPanel$0(LoadFilePanel.java:60)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by i-make-robots** [comment]
Converter_VoronoiStippling.initializeCells() is probably the guilty party.

**Comment by i-make-robots** [comment]
The idenpendent test (run ImageConverterPanel as a java application) crashes with error message immediately.
Fixed that and now the app runs up to the conversion options but then several options do not have cause-and-effect.  eg i change the config options inside crosshatch and nothing changes on screen because the converter does not restart.

A lot of this code is spaghetti because it tried to work nice with single-pass converters like cross hatch and iterative converters like voronoi stippling.

**Comment by i-make-robots** [comment]
b5d9be1c should fix everything.

**Comment by i-make-robots** [comment]
It would be awesome if we had an AssertJ unit test for this behavior to make sure it never happens again.

**Comment by coliss86** [comment]
Fix confirmed !

**Comment by coliss86** [comment]
Can you tell me what did you run to reproduced the problem ? I can try to implement is as a test

**Comment by i-make-robots** [comment]
I followed your steps, as described in the OP.

**Comment by PPAC37** [comment]
Oops ... my apologies! the problem from here was related to the fixes to fix my LookAndFeel problem
https://github.com/MarginallyClever/Makelangelo-software/issues/365
and with this last fix my problem and come back.

But I have the option of using -nolf to bypass it ... so I'll leave it at that for now. (Mom problem and closed because I can bypass it and this one too.)

**Comment by coliss86** [comment]
> I followed your steps, as described in the OP.

You said previously : "The idenpendent test (run ImageConverterPanel as a java application) crashes with error message immediately." but I can't find any runnable method. May be I didn't understood what you mean.
